### ISSUE TITLE
Command missing for production

### ISSUE THREAD

**Issue by bl0way** [ClarifiedSecurity/Providentia#24]
Hello!
After some troubleshooting, it appears that some extra command are necessary to deploy the production part.
Instead of:
```bash
cd docker/prod
docker compose -f docker-compose.yml -f proxy.yml up -d
```
This, should work (at least for me it worked):
```
git describe --tags >CURRENT_VERSION
cd docker/prod
docker compose -f docker-compose.yml -f proxy.yml build
docker compose -f docker-compose.yml -f proxy.yml up -d
```
Moreover, if I am not mistaking, an user (with uid 1000) needs to be created and permissions for files adjusted accordingly

**Comment by mromulus** [comment]
This should be improved with completion of #28: you can use `make config` (choose production), `make build` and `make start`
